### ISSUE TITLE
about the dataset

### ISSUE THREAD

**Issue by ai1361720220000** [bmycheez/C3Net#2]
hello, thanks for your sharing in this nice project with relative trained models. But i can't find the downloading link of the CFAMoire dataset, mayby because the competition is over. Could you send me this dataset? my email 136172022@qq.com. 

Thanks ~

**Comment by haimin777** [comment]
Yes, it will be fine to get this data). Is it possible?

**Comment by hermosayhl** [comment]
> > Yes, it will be fine to get this data). Is it possible?
> 
> i have downloaded the dataset after registration.

Could you please provide the download links for me? I have tried many times and nothing replied after registration.

**Comment by bmycheez** [comment]
Please get NTIRE 2020 Demoireing Challenge data from this [link](https://competitions.codalab.org/competitions/22224).
When you sign in and participate in challenge, you can get the data.
If not any response, please contact to [Radu](http://www.vision.ee.ethz.ch/~timofter/), the host of the challenge.

**Comment by nafe93** [comment]
Hi,

I’m a PhD student working on image restoration and demoireing. I saw that the NTIRE 2020 Demoireing Challenge used the CFAMoire dataset, but the original CodaLab link seems to be closed now.

Would it be possible for someone to share the dataset, or point me to where I can still download it? It would be very helpful for my research.

Thanks in advance!

**Comment by bmycheez** [comment]
Unfortunately, I don't have any dataset.
I confirmed that the challenge link does not offer the dataset anymore.
You can contact to challenge chairs such as [Radu](https://cvlai.net/).

**Comment by bmycheez** [comment]
> Hi,
> 
> I’m a PhD student working on image restoration and demoireing. I saw that the NTIRE 2020 Demoireing Challenge used the CFAMoire dataset, but the original CodaLab link seems to be closed now.
> 
> Would it be possible for someone to share the dataset, or point me to where I can still download it? It would be very helpful for my research.
> 
> Thanks in advance!

Unfortunately, I don't have any dataset.
I confirmed that the challenge link does not offer the dataset anymore.
You can contact to challenge chairs such as [Radu](https://cvlai.net/).

**Comment by bmycheez** [comment]
> > Hi,
> > I’m a PhD student working on image restoration and demoireing. I saw that the NTIRE 2020 Demoireing Challenge used the CFAMoire dataset, but the original CodaLab link seems to be closed now.
> > Would it be possible for someone to share the dataset, or point me to where I can still download it? It would be very helpful for my research.
> > Thanks in advance!
> 
> Unfortunately, I don't have any dataset. I confirmed that the challenge link does not offer the dataset anymore. You can contact to challenge chairs such as [Radu](https://cvlai.net/).

Plus, the challenge paper says that:
- The clean images are sampled or cropped from existing datasets, including DeepJoint, HDR+, and DIV8K.
- The corresponding moire images are generated through a remosaicing and demosaicing process, where
moire artifacts will appear in the high frequency area.

Maybe, you or I can try of them and regenerate the dataset!
